apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-config
  namespace: user-management
data:
  # Environment
  ENVIRONMENT: "${ENVIRONMENT}"

  # PostgreSQL Database Settings
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_SCHEMA: "${POSTGRES_SCHEMA}"
  POSTGRES_USER: "${POSTGRES_USER}"

  # Redis Server Settings
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_PORT: "${REDIS_PORT}"
  REDIS_DB: "${REDIS_DB}"

  # OAuth2 Settings
  OAUTH2_ENABLED: "${OAUTH2_ENABLED}"
  OAUTH2_SERVICE_ENABLED: "${OAUTH2_SERVICE_ENABLED}"
  OAUTH2_INTROSPECTION_ENABLED: "${OAUTH2_INTROSPECTION_ENABLED}"
  OAUTH2_CLIENT_ID: "${OAUTH2_CLIENT_ID}"
