---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gateway.networking.k8s.io/generator: ingress2gateway-0.4.0
  name: user-management-ingress-user-management.local
  namespace: user-management
spec:
  hostnames:
    - user-management.local
    - sous-chef-proxy.local
  parentRefs:
    - name: kong
      namespace: kong
  rules:
    - backendRefs:
        - name: user-management-service
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /api/v1/user-management
status:
  parents: []
