apiVersion: v1
kind: Secret
metadata:
  name: user-management-secrets
  namespace: user-management-dev-poc
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
