apiVersion: v1
kind: Secret
metadata:
  name: user-management-secrets
  namespace: user-management
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  OAUTH2_CLIENT_SECRET: "${OAUTH2_CLIENT_SECRET}"
  OAUTH2_JWT_SECRET: "${OAUTH2_JWT_SECRET}"
