logging:
  consoleEnabled: true
  consoleLevel: info
  fileEnabled: true
  fileLevel: debug
  format: json
  file: ./logs/user-management-service.log
  maxSize: 100
  maxBackups: 3
  maxAge: 28
  compress: true
